### ISSUE TITLE
老哥求教一下这是什么问题

### ISSUE THREAD

**Issue by HuTaoLoveFurina** [Colorfulshadow/coalcloud_grab_vps#1]
![image](https://github.com/Colorfulshadow/coalcloud_grab_vps/assets/73696739/864b432a-7dc6-4969-afee-8989390dfd19)

**Comment by Colorfulshadow** [comment]
[https://peps.python.org/pep-0668/](https://peps.python.org/pep-0668/)

note、hint和error提示的很清楚，建议以后先google再询问。
